### ISSUE TITLE
Goblin state is assumed dead when returning from Upper Door.

### ISSUE THREAD

**Issue by luigi-rosso** [filiph/edgehead#15]
I stole the Goblin's shield after the Smooth Passage leading to the Upper Door. I chose to go to the Upper Door and was prompted to return. The next line of text mentions the goblin is sprawled out dead on the floor.

![image](https://user-images.githubusercontent.com/454182/40209905-f1a74b7c-59f6-11e8-8bf1-f75b3d3a9596.png)

**Comment by filiph** [comment]
Good catch! This has been fixed in the dev version (`master` branch) but not in the https://github.com/filiph/edgehead/tree/vermin2017 version (which is the one playable online). I don't think I'll have time to go back and fix this in the web version.
